(() => {
  "use strict";
  const navActions=document.querySelector(".nav-actions");
  if(!navActions)return;
  if(!document.querySelector('link[data-spectra-education-css]')){const l=document.createElement("link");l.rel="stylesheet";l.href="education.css";l.dataset.spectraEducationCss="true";document.head.appendChild(l)}
  const trigger=document.createElement("button");trigger.type="button";trigger.className="education-trigger";trigger.textContent="EDUCATION";trigger.setAttribute("aria-haspopup","dialog");trigger.setAttribute("aria-expanded","false");navActions.appendChild(trigger);
  const overlay=document.createElement("div");overlay.className="education-overlay";overlay.setAttribute("aria-hidden","true");overlay.innerHTML='<section class="education-panel" role="dialog" aria-modal="true" aria-label="SPECTRA Education"><button class="education-close" type="button" aria-label="Close Education"></button><div class="education-content"></div></section>';document.body.appendChild(overlay);
  const content=overlay.querySelector(".education-content"),close=overlay.querySelector(".education-close");let loaded=false,lastFocus=null;
  async function load(){if(loaded)return;content.innerHTML='<div style="padding:120px 6vw;color:#657783;font:11px var(--mono)">LOADING EDUCATION...</div>';try{const r=await fetch("education.html",{cache:"no-cache"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=new DOMParser().parseFromString(await r.text(),"text/html");content.replaceChildren(...Array.from(d.body.children));loaded=true;wire()}catch(e){content.innerHTML='<div style="padding:120px 6vw;color:#8b98a1;font:12px var(--mono)">EDUCATION COULD NOT BE LOADED.<br><br>Make sure education.html is in the same folder as index.html.</div>';console.error("SPECTRA Education:",e)}}
  function wire(){
    const page=content.querySelector(".education-page"),selector=content.querySelector(".level-selector"),library=content.querySelector(".education-library"),cards=[...content.querySelectorAll("[data-level-choice]")],tabs=[...content.querySelectorAll("[data-filter]")],selected=content.querySelector(".selected-level"),groups=[...content.querySelectorAll(".edu-group")],search=content.querySelector("#education-search-input"),levelIndex=content.querySelector(".selected-level-index"),levelName=content.querySelector(".selected-level b"),title=content.querySelector("#library-title");
    const meta={beginner:["01","BEGINNER","Build the foundation"],advanced:["02","ADVANCED","Read what is happening"],expert:["03","EXPERT","Read the mechanics"]};let active="beginner";
    function setLevel(level,animate=true){active=level;const [n,name,heading]=meta[level];page.classList.add("level-selected");levelIndex.textContent=n;levelName.textContent=name;title.textContent=heading;tabs.forEach(t=>t.classList.toggle("is-active",t.dataset.filter===level));groups.forEach(g=>{g.classList.toggle("education-hidden",g.dataset.level!==level);g.querySelector(".group-title").setAttribute("aria-expanded","false");g.querySelector(".group-body").hidden=true;g.querySelector(".group-toggle").textContent="+"});if(search)search.value="";if(animate)library.scrollIntoView({behavior:"smooth",block:"start"})}
    function resetLevel(){page.classList.remove("level-selected");groups.forEach(g=>{g.classList.remove("education-hidden");g.querySelector(".group-title").setAttribute("aria-expanded","false");g.querySelector(".group-body").hidden=true;g.querySelector(".group-toggle").textContent="+"});search.value="";window.setTimeout(()=>selector.querySelector(`[data-level-choice="${active}"]`)?.focus(),120)}
    cards.forEach(c=>c.addEventListener("click",()=>setLevel(c.dataset.levelChoice)));tabs.forEach(t=>t.addEventListener("click",()=>setLevel(t.dataset.filter)));selected?.addEventListener("click",resetLevel);
    groups.forEach(g=>{const b=g.querySelector(".group-title"),body=g.querySelector(".group-body"),toggle=g.querySelector(".group-toggle");b.addEventListener("click",()=>{const open=b.getAttribute("aria-expanded")==="true";groups.forEach(o=>{if(o!==g){o.querySelector(".group-title").setAttribute("aria-expanded","false");o.querySelector(".group-body").hidden=true;o.querySelector(".group-toggle").textContent="+"}});b.setAttribute("aria-expanded",String(!open));body.hidden=open;toggle.textContent=open?"+":"−"})});
    search?.addEventListener("input",()=>{const q=search.value.trim().toLowerCase();groups.forEach(g=>{const match=g.dataset.level===active && (!q || (g.dataset.search+" "+g.textContent).toLowerCase().includes(q));g.classList.toggle("education-hidden",!match)})});
  }
  function open(){lastFocus=document.activeElement;overlay.classList.add("is-open");overlay.setAttribute("aria-hidden","false");trigger.setAttribute("aria-expanded","true");document.body.classList.add("education-locked");load();document.querySelector(".menu-toggle")?.setAttribute("aria-expanded","false");document.querySelector(".nav-actions")?.classList.remove("mobile-open");window.setTimeout(()=>close.focus(),100)}
  function shut(){overlay.classList.remove("is-open");overlay.setAttribute("aria-hidden","true");trigger.setAttribute("aria-expanded","false");document.body.classList.remove("education-locked");window.setTimeout(()=>lastFocus?.focus?.(),150)}
  trigger.addEventListener("click",open);close.addEventListener("click",shut);overlay.addEventListener("click",e=>{if(e.target===overlay)shut()});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&overlay.classList.contains("is-open"))shut()});
})();
